### ISSUE TITLE
Hiding Background Texts on Homepage

### ISSUE THREAD

**Issue by jomi615** [canopas/nuxt-blog-kit#37]
Hey there, I noticed that there are three background words "Blogs", "Our Portfolio", and "Services" on the homepage of Canopas. I would suggest either hiding them to make the section title format cohesive with the rest of the page (The "We are here to contribute" section), or making them become part of the section instead of just being in the background.

**Comment by cp-dharti-r** [comment]
Hey @jomi615, Thanks for your suggestion!
We’ll definitely look into either making these background words part of the respective sections or adjusting them to fit the overall design better.
